name: Deploy to Hostinger

on:
  push:
    branches: [main] # 如果默认分支是 master 就改成 master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      # 可视化确认：给 dist 放一个标记文件，部署后在服务器能看到1
      - name: Add deploy marker
        run: echo $GITHUB_SHA > dist/__deployed_commit.txt

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: dist/ # 结尾必须有 /
          server-dir: ./ # ✅ 新账号登录即是 4everyang.com 的 public_html
          dangerous-clean-slate: true
          log-level: verbose
